app_client:
    resource: "@AppClientBundle/Resources/config/routing.yml"
    prefix:   /

app_server:
   resource: "@AppServerBundle/Resources/config/routing.yml"
   prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"