_home:
    path:     /
    defaults: { _controller: AppClientBundle:App:home }

app_client_depot_list:
    path:     /depot/list
    defaults: { _controller: AppClientBundle:Depot:list }

app_client_depot_show:
    path:     /depot/{id}
    defaults: { _controller: AppClientBundle:Depot:show }

app_client_ajax_action:
  path: /ajax/action
  defaults: { _controller: AppClientBundle:AjaxAction:ajax }
